### ISSUE TITLE
Add idaplugins-list

### ISSUE THREAD

**Issue by bartblaze** [fr0gger/awesome-ida-x64-olly-plugin#5]
Thanks Thomas for a great list. 

It could be worth either adding the plugins on [idaplugins-list](https://github.com/onethawt/idaplugins-list) on here as well, or perhaps embed that repo as a submodule?

Cheers
Bart

**Comment by fr0gger** [comment]
Thanks for your comment Bart! 

Indeed it could be nice to add a subcategory with the existing list. :)
